1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

ans--NumPy enhances Python's capabilities for numerical operations by providing fast, efficient array processing, supporting large multi-dimensional arrays and matrices, and offering a wide range of mathematical functions. Its purpose is to enable high-performance scientific computing and data analysis by optimizing operations using vectorization, which avoids Python loops and leverages optimized C code for speed. This makes numerical computations significantly faster and more memory-efficient than using Python's built-in data structures.

2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

ans--`np.mean()` calculates the simple arithmetic mean of array elements without considering weights, making it suitable for straightforward average calculations. In contrast, `np.average()` can compute a weighted average, where each element can have a different level of influence. Use `np.mean()` for basic averaging needs and `np.average()` when you need to account for weights in your data.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

ans--To reverse a NumPy array, you can use slicing or the np.flip() function:

1D Array: You can reverse a 1D array using slicing:

In [3]:
import numpy as np # import the numpy library and alias it as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]  # Output: [5, 4, 3, 2, 1]
print(reversed_arr)

[5 4 3 2 1]


In [5]:
#2D array

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_arr = arr[::-1, ::-1]  # Output: [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
print(reversed_arr)


[[9 8 7]
 [6 5 4]
 [3 2 1]]


 4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

ans--
You can determine the data type of elements in a NumPy array using the .dtype attribute:


In [7]:
arr = np.array([1, 2, 3])
print(arr.dtype)


int64


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

ans--ndarrays in NumPy are multi-dimensional arrays that store elements of the same data type in a contiguous block of memory. Key features include support for high-performance vectorized operations, built-in mathematical functions, and efficient slicing and indexing.

Compared to standard Python lists, ndarrays offer:

Faster computation: They use optimized C code under the hood.
Lower memory usage: They store data more compactly.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

ans--NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations. This is because NumPy arrays use contiguous blocks of memory and are implemented in C, enabling them to perform vectorized operations without the need for Python loops. This results in faster execution and more efficient memory usage.

For large datasets, NumPy's operations are highly optimized, often running orders of magnitude faster than equivalent operations with Python lists. Additionally, arrays have built-in functions for complex computations, which further speeds up processing compared to iterating manually with lists. This makes NumPy a powerful tool for handling large-scale numerical tasks efficiently.


7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.


vstack() and hstack() in NumPy are used to stack arrays together vertically and horizontally, respectively:

vstack(): Stacks arrays vertically (row-wise).

In [8]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


In [9]:
#hstack(): Stacks arrays horizontally (column-wise).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.hstack((arr1, arr2))
print(result)



[1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

ans--fliplr() and flipud() in NumPy are used to flip arrays along different axes:

fliplr(): Flips an array left to right (horizontally). It affects the columns of a 2D array by reversing their order.

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.fliplr(arr)
print(result)


[[3 2 1]
 [6 5 4]]


In [11]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.flipud(arr)
print(result)

[[4 5 6]
 [1 2 3]]


9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

The array_split() method in NumPy splits an array into specified sub-arrays. Unlike split(), it can handle cases where the array can't be split evenly. If the array's length doesn't divide evenly by the number of splits, array_split() ensures that sub-arrays will vary slightly in size, with some being larger than others.

In [12]:
arr = np.array([1, 2, 3, 4, 5])
splits = np.array_split(arr, 3)
print(splits)


[array([1, 2]), array([3, 4]), array([5])]


10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?


Vectorization and broadcasting in NumPy are techniques that make array operations faster and more efficient by reducing the need for explicit loops.

Vectorization allows you to perform operations on entire arrays at once, rather than looping through individual elements. This leverages optimized, low-level code, often written in C, making it much faster than traditional Python loops.

Broadcasting enables NumPy to handle arrays of different shapes in operations. For example, you can add a 1D array to a 2D array without explicitly reshaping. NumPy automatically “stretches” the smaller array along the necessary dimensions, allowing operations on mismatched shapes without additional memory overhead.

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [13]:
import numpy as np
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:")
print(array)


Original Array:
[[ 64 100  58]
 [ 39  20  45]
 [ 94   4  31]]


To interchange rows and columns (transpose the array), use array.T:

In [14]:
transposed_array = array.T
print("Transposed Array:")
print(transposed_array)


Transposed Array:
[[ 64  39  94]
 [100  20   4]
 [ 58  45  31]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

First, create a 1D NumPy array with 10 elements:

In [15]:
import numpy as np
array = np.arange(10)
print("Original 1D Array:")
print(array)


Original 1D Array:
[0 1 2 3 4 5 6 7 8 9]


In [16]:
#Reshape it into a 2x5 array:

array_2x5 = array.reshape(2, 5)
print("2x5 Array:")
print(array_2x5)


2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
#Then reshape it into a 5x2 array:

array_5x2 = array.reshape(5, 2)
print("5x2 Array:")
print(array_5x2)


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [19]:
import numpy as np
array = np.random.rand(4, 4)
print("Original 4x4 Array:")
print(array)


Original 4x4 Array:
[[0.77952743 0.59015128 0.86894735 0.58185911]
 [0.33496983 0.76297718 0.5567609  0.7034811 ]
 [0.35700909 0.39010019 0.90360388 0.5981553 ]
 [0.17234947 0.09476375 0.04183607 0.68582851]]


In [20]:
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print("6x6 Array with Border of Zeros:")
print(bordered_array)


6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.77952743 0.59015128 0.86894735 0.58185911 0.        ]
 [0.         0.33496983 0.76297718 0.5567609  0.7034811  0.        ]
 [0.         0.35700909 0.39010019 0.90360388 0.5981553  0.        ]
 [0.         0.17234947 0.09476375 0.04183607 0.68582851 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [17]:
import numpy as np
array = np.arange(10, 65, 5)
print(array)

[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.  5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.


In [18]:
import numpy as np

# Create the array of strings
array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(array)
lowercase_array = np.char.lower(array)
titlecase_array = np.char.title(array)

print("Original Array:", array)
print("Uppercase:", uppercase_array)
print("Lowercase:", lowercase_array)
print("Title Case:", titlecase_array)


Original Array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array

In [22]:
import numpy as np
words = np.array(['python', 'numpy', 'pandas'])
print("Original Array:", words)
spaced_words = np.char.join(' ', words)
print("Spaced Array:", spaced_words)

Original Array: ['python' 'numpy' 'pandas']
Spaced Array: ['p y t h o n' 'n u m p y' 'p a n d a s']


7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [23]:
import numpy as np
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [24]:
import numpy as np
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [25]:
diagonal_elements = np.diag(identity_matrix)
print("Diagonal Elements:")
print(diagonal_elements)

Diagonal Elements:
[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.



In [26]:
import numpy as np
array = np.random.randint(0, 1000, 100)
print("Array of 100 Random Integers:")
print(array)


Array of 100 Random Integers:
[231 877 532 218 164 867 255 680 711 573 760 299 309 748  41 144 458 288
 587 178 121 935 695 138 746 144 647 634 426  68 388 278 629 288 276 631
 637 155  39 293 637 379 246  33 263  62 709 563 584 237   2 454 148 955
 756  48 220 686 780  44 493 975 593 820 482 680 872 679 717  26 970 704
 193 677 906 216 735 336 727 583 741 598 553  95 625 598 189 527 991 457
 205 671 614 514 383 240 358 771 742 534]


In [28]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
    print("Prime Numbers:")
prime_numbers = [num for num in array if is_prime(num)]
print(prime_numbers)


[877, 41, 587, 647, 631, 293, 379, 263, 709, 563, 2, 593, 193, 677, 727, 991, 457, 383]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [33]:
import numpy as np
# Example temperatures between 20 and 35 degrees Celsius
daily_temperatures = np.random.randint(20, 36, size=30)
print("Daily Temperatures for a Month:")
print(daily_temperatures)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)  # Only take the first 28 days for full weeks
print("\nTemperatures Reshaped into Weeks:")
print(weekly_temperatures)
weekly_temperatures = daily_temperatures[:28].reshape(4, 7)  # Only take the first 28 days for full weeks
print("\nTemperatures Reshaped into Weeks:")
print(weekly_temperatures)




Daily Temperatures for a Month:
[34 27 27 27 30 31 20 22 28 23 31 22 27 35 29 32 30 29 34 23 34 28 22 23
 28 24 30 20 29 22]

Temperatures Reshaped into Weeks:
[[34 27 27 27 30 31 20]
 [22 28 23 31 22 27 35]
 [29 32 30 29 34 23 34]
 [28 22 23 28 24 30 20]]

Temperatures Reshaped into Weeks:
[[34 27 27 27 30 31 20]
 [22 28 23 31 22 27 35]
 [29 32 30 29 34 23 34]
 [28 22 23 28 24 30 20]]
